[cuboid]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

point_plane_range = [50, 100]
endpoint_equinox_range = [0.2, 0.8]
height_range = [20, 50]
bottom_y_range = [0, 5]
dip_degree_range = [-10, 45]
endpoint_dithering = [0, 3]

[cone]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

radius_range = [5, 40]
height_range = [20, 50]
endpoint_dithering = [0, 3]

[cylinder]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

a_range = [20, 50]
b_range = [10, 30]
height_range = [20, 50]
bottom_y_range = [0, 5]
dip_degree_range = [-10, 45]
endpoint_dithering = [0, 3]

[hemisphere]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

r_range = [10, 30]
bottom_y_range = [0, 5]
th_degree_range = [20, 90]

[pyramid]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

point_num_range = [3, 8]
point_plane_range = [-50, 50]
height_range = [50, 80]
bottom_y_range = [0, 5]
endpoint_dithering = [0, 3]

[shed]
density = 0.2
equinox_range = [0.5, 0.5]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

point_x_range = [20, 60]
th_degree_range = [60, 90]
r_range = [20, 40]
bottom_y_range = [0, 2]
arc_rot_degree_range = [0, 10]
endpoint_dithering = [0, 1]

[platform]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

point_bottom_plane_range = [50, 100]
point_top_plane_range = [10, 30]
height_range = [20, 50]
bottom_y_range = [0, 5]
endpoint_dithering = [0, 3]

[hip]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.2]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

point_bottom_plane_range = [70, 70]
point_top_x_range = [70, 70]
point_top_z_range = [0, 5]
height_range = [20, 30]
bottom_y_range = [0, 5]
endpoint_dithering = [0, 5]

[freeform]
density = 0.2
equinox_range = [0.3, 0.7]
point_dithering = [0.0, 0.0]
plane_rotate_degree_range = [0, 360]
move_plane_range = [-50, 50]
move_y_range = [0, 10]

point_num_range = [3, 10]
dip_degree_range = [-10, 30]
point_plane_range = [-100, 100]
height_range = [30, 50]
bottom_y_range = [5, 5]
curve_poss = 0.5
line_endpoint_dithering = [0, 0]
curve_endpoint_dithering = [5, 10]
